# Generated by Django 3.1.2 on 2020-10-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3App', '0004_auto_20201006_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.CharField(choices=[('HS', 'High School'), ('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('ND', 'No Degree')], default='HS', max_length=2),
        ),
    ]
