# Generated by Django 3.1.2 on 2020-12-02 02:24

import Lab3App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab3App', '0010_course_num_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_Img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[Lab3App.models.validate_price]),
        ),
    ]
